### PR TITLE
Add version var in twig for cache busting

### LINKED ISSUE #18: replace @version placeholder by a twig variable to make it works on 3rd system

### PR DESCRIPTION
**Pull request by samouss**
Fix #18

### CODE REVIEW

**Comment by pitpit** [comment]
What about index.html `@@version` placeholder ? Does it works again ?

https://github.com/creads/cakepan/blob/master/src/index.html#L15

**Comment by samouss** [comment]
Yes it works.

Because the HTML task keep the replacement function, see: 

https://github.com/samouss/cakepan/blob/d133ea04900b5a04bca69484f06b9578896f45ec/gulpfile.js#L163

We simply add a twig var with the actual version, see:

https://github.com/samouss/cakepan/blob/d133ea04900b5a04bca69484f06b9578896f45ec/gulpfile.js#L182

**Comment by samouss** [comment]
up!

**Comment by pitpit** [comment]
thanks !

**Pull request merged**
