### PR TITLE
Add way for override config via opitons

### LINKED ISSUE #20: add a magic parameter scanner allowing to override any parameter
ie:
```
gulp --prod=true --build="../../sample"
```

will set config to:

```
{
  "prod": true
  "build": "../../sample"
}
```

### PR DESCRIPTION
**Pull request by samouss**
Fix #20

### CODE REVIEW

**Comment by pitpit** [comment]
can you merge it with master pls ?

**Comment by samouss** [comment]
I wait the merge of #22

**Comment by samouss** [comment]
up!

**Comment by pitpit** [comment]
can you merge the master in it

**Comment by samouss** [comment]
Ok.

**Comment by samouss** [comment]
up!

**Comment by pitpit** [comment]
thanks !

**Pull request merged**
